In [1]:
import numpy as np
import pandas as pd

In [4]:
patients = pd.read_csv('C:\\Users\\gyanr\\OneDrive\\Desktop\\Dash\\Covid_19\\IndividualDetails.csv')
patients

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30/01/2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
1,1,KL-AL-P1,02/02/2020,NaN,NaN,Alappuzha,Alappuzha,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
2,2,KL-KS-P1,03/02/2020,NaN,NaN,Kasaragod,Kasaragod,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
3,3,DL-P1,02/03/2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15/03/2020,"Travelled from Austria, Italy"
4,4,TS-P1,02/03/2020,24,M,Hyderabad,Hyderabad,Telangana,India,Recovered,02/03/2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8467,8468,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8468,8469,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8469,8470,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8470,8471,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8471,8472,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN

In [5]:
patients['current_status'].value_counts()

current_status
Hospitalized    8301
Recovered        139
Deceased          30
Migrated           1
Name: count, dtype: int64

In [31]:
totalpatients = patients.shape[0]
active = patients[patients['current_status'] == 'Hospitalized'].shape[0]
recovered = patients[patients['current_status'] == 'Recovered'].shape[0]
deaths = patients[patients['current_status'] == 'Deceased'].shape[0]

In [32]:
active = patients[patients['current_status'] == 'Hospitalized'].shape[0]

In [8]:
patients

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30/01/2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
1,1,KL-AL-P1,02/02/2020,NaN,NaN,Alappuzha,Alappuzha,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
2,2,KL-KS-P1,03/02/2020,NaN,NaN,Kasaragod,Kasaragod,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
3,3,DL-P1,02/03/2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15/03/2020,"Travelled from Austria, Italy"
4,4,TS-P1,02/03/2020,24,M,Hyderabad,Hyderabad,Telangana,India,Recovered,02/03/2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8467,8468,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8468,8469,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8469,8470,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8470,8471,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8471,8472,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN

In [34]:
npat = patients[patients['current_status'] == 'Recovered']
pbar = npat['detected_state'].value_counts().reset_index()
# patients.groupby('detected_state')['current_status'].count()

In [35]:
pbar

      detected_state  count
0             Kerala     58
1          Karnataka     39
2            Haryana     12
3      Uttar Pradesh      6
4         Tamil Nadu      6
5          Rajasthan      3
6        West Bengal      3
7              Delhi      2
8     Andhra Pradesh      2
9        Maharashtra      2
10         Telangana      1
11      Chhattisgarh      1
12       Uttarakhand      1
13           Gujarat      1
14  Himachal Pradesh      1
15           Manipur      1

In [36]:
npat

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30/01/2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
1,1,KL-AL-P1,02/02/2020,NaN,NaN,Alappuzha,Alappuzha,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
2,2,KL-KS-P1,03/02/2020,NaN,NaN,Kasaragod,Kasaragod,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
3,3,DL-P1,02/03/2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15/03/2020,"Travelled from Austria, Italy"
4,4,TS-P1,02/03/2020,24,M,Hyderabad,Hyderabad,Telangana,India,Recovered,02/03/2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
1078,1078,TN-P46,29/03/2020,51,F,NaN,Erode,Tamil Nadu,India,Recovered,06/04/2020,Contact of TN-P43
1248,1248,NaN,30/03/2020,NaN,NaN,NaN,Kannur,Kerala,NaN,Recovered,04/04/2020,Details awaited
1249,1249,NaN,30/03/2020,NaN,NaN,NaN,Kannur,Kerala,NaN,Recovered,05/04/2020,Details awaited
1250,1250,NaN,30/03/2020,NaN,NaN,NaN,Kannur,Kerala,NaN,Recovered,05/04/2020,Details awaited
1260,1260,NaN,30/03/2020,NaN,NaN,NaN,Wayanad,Kerala,NaN,Recovered,08/04/2020,Details awaited